### ISSUE TITLE
ISS verifies signers of checkpoint message with info from checkpoint message

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/mir#397] opened 2023-04-10 04:29 UTC
As noted in the code already:
```
// TODO: Technically this is wrong.
	//       The memberhips information in the checkpint is used to verify the checkpoint itself.
	//       This makes it possible to construct an arbitrary valid checkpoint.
	//       Use an independent local source of memberhip information instead.
```

Making this placeholder in order to fix it for M2.

**Comment by matejpavlovic** [comment] 2023-04-25 08:26
@ranchalp is this a duplicate of #402 ?

**Closed** 2023-04-25 08:36 UTC
Labels: bug, cleanup, M2
